name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Test Pact-Ruby Specs
        run: "bundle exec rake"
      - name: Test Pact-Ruby sbmt Specs
        run: "bundle exec rake spec:sbmt"
      - name: Test Pact-Ruby Zoo App Specs
        run: "bundle install && bundle exec rake spec"
        if: matrix.ruby_version > '3.0'
        working-directory: example/zoo-app
      - name: Test Pact-Ruby Animal Service Specs
        run: "bundle install && bundle exec rake pact:verify"
        if: matrix.os != 'windows-latest' && matrix.ruby_version > '3.0'
        working-directory: example/animal-service
      - name: Test Pact-Ruby sbmt Zoo App Specs
        run: "bundle install && bundle exec rake spec:sbmt"
        if: matrix.ruby_version > '3.0'
        working-directory: example/zoo-app-sbmt
      - name: Test Pact-Ruby sbmt Animal Service Specs
        run: "bundle install && bundle exec rake pact:sbmt:verify"
        if: matrix.os != 'windows-latest' && matrix.ruby_version > '3.0'
        working-directory: example/animal-service-sbmt

  test-with-rack-2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.2"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: "bundle exec appraisal install"
      - run: "bundle exec appraisal rack-2 rake"
  test-with-active-support:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: "bundle exec appraisal install"
        name: "install active support - pact-ruby"
        env:
          PACT_RUBY_V2_DISABLE: 'true'
      - run: "bundle exec appraisal activesupport rake spec_with_active_support"
        name: "test with active support - pact-ruby"
        env:
          PACT_RUBY_V2_DISABLE: 'true'
      - run: rm -rf Gemfile.lock gemfiles
        shell: bash
      - run: "bundle install"
        name: "bundle install - pact-ruby v2"
        env:
          LOAD_ACTIVE_SUPPORT: 'true'
      - run: "bundle exec rake spec:sbmt"
        name: "test with active support - pact-ruby v2"
        env:
          LOAD_ACTIVE_SUPPORT: 'true'